const MANUAL = {
  // Root screens
  ROOT: 'ROOT',
  // Other screen
  ADD_NEW_TOPIC: 'ADD_NEW_TOPIC',
  ADD_NEW_CARD: 'ADD_NEW_CARD',
  CHOOSE_ICON: 'CHOOSE_ICON',
  FLASHCARD_LIST: 'FLASHCARD_LIST',
  FLASHCARD: 'FLASHCARD',
  TOPIC_LIST: 'TOPIC_LIST',
} as const;

const ROOT = {
  HOME_SCREEN: 'HOME_SCREEN',
  ADD_CARD_SCREEN: 'ADD_CARD_SCREEN',
  ACCOUNT_SCREEN: 'ACCOUNT_SCREEN',
} as const;

export default {MANUAL, ROOT};
